### ISSUE TITLE
ios 9.1

### ISSUE THREAD

**Issue by DKalachniuk** [mapswithme/api-ios#10]
[MWMApi isApiSupported] in ios9.1 returns NO
is was working in ios 9.0
please check!

**Comment by deathbaba** [comment]
That's strange. @igrechuhin @VladiMihaylenko Can you please check it out?

**Comment by DKalachniuk** [comment]
What I did, I put into info.plist LSApplicationQueriesSchemes and value mapswithme
and it is working. I think you need to put this information to the documentation
